enum Cities
{
    Addis Abeba,
    Bahrel Ghazal,
    Cairo,
    Congo,
    Dafur,
    Dakar,
    De Kanariske Øer,
    Dragebjerget,
    Guld Kysten,
    Hvalbugten,
    Kabalo,
    Kap Guardafui,
    Kap St. Marie,
    Kapstaden,
    Luanda,
    Marrakesh,
    Mocambique,
    Omdurman,
    Sahara,
    Sierra Leone,
    Slave Kysten,
    St. Helena,
    Suakin,
    Tamatave,
    Tanger,
    Timbuktu,
    Tripoli,
    Tunis,
    Victoriafaldene,
    Victoriasøen,
    Wadai,
    Zanzibar
}