//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace telstarapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Connection
    {
        public int ConnectionId { get; set; }
        public Nullable<int> City1 { get; set; }
        public Nullable<int> City2 { get; set; }
        public Nullable<int> TimeOfOneSegmentInHours { get; set; }
        public Nullable<double> PriceOfOneSegment { get; set; }
        public Nullable<int> Owner { get; set; }
        public Nullable<int> NumberOfSegments { get; set; }
    
        public virtual City City { get; set; }
        public virtual City City3 { get; set; }
    }
}
