//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace telstarapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderId { get; set; }
        public Nullable<double> OurPrice { get; set; }
        public Nullable<double> OtherPrice { get; set; }
        public Nullable<int> Hours { get; set; }
        public Nullable<byte> PaidStatus { get; set; }
        public Nullable<int> Package { get; set; }
        public Nullable<int> User { get; set; }
        public string Route { get; set; }
    
        public virtual Package Package1 { get; set; }
        public virtual User User1 { get; set; }
    }
}
